version: '3.8'
services:
  db:
    image: ds10x2/mysqldb:1.2
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: manageuser
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - db-data:/var/lib/mysqldb
    networks:
      - network
    command: --default-authentication-plugin=mysql_native_password

  jsserver:
    image: ds10x2/jsserver-sql:1.2
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root1234
      DB_NAME: manageuser
    networks:
      - network

volumes:
  db-data:

networks:
  network:
    driver: bridge